config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :charges, only: [:new, :create]
  resources :downgrades, only: [:new, :create]
  resources :wikis do
    resources :collaborators, only: [:index, :new, :create]
  end

  post 'downgrade/create'

  get 'about' => 'welcome#about'
    root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
   after_initialize :give_standard_role
   has_many :wikis
   has_many :collaborators
   has_many :collaborate_wikis, through: :collaborators, source: :wiki

   validates :role, presence: true

   enum role: [:standard, :premium, :admin]
   private

   def give_standard_role
    self.role ||= :standard
   end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :collaborate_users, through: :collaborators, source: :user

  default_scope {order('created_at DESC')}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotDefinedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to change or remove this wiki."
    render :show
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

   def create
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )

     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: 15_00,
       description: "Blocipedia Membership - #{current_user.email}",
       currency: 'usd'
     )

     current_user.update_attribute(:standard, false)
     current_user.update_attribute(:premium, true)

     flash[:notice] = "Thank you for upgrading your account to Premium, #{current_user.email}!"

     redirect_to root_path

     # Stripe will send back CardErrors, with friendly messages
     # when something goes wrong.
     # This `rescue block` catches and displays those errors.
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
   end

   def new
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Blocipedia membership - #{current_user.email}",
       amount: 15_00
     }
   end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators = @wiki.collaborate_users.all
  end

  def new
    @wiki = Wiki.find(params[:wiki_id])
    authorize(@wiki.collaborators)
  end

  def create
    wiki = Wiki.find(params[:wiki_id])
    collaborators = []
    wiki.collaborators.destroy_all
    params[:collaborators].each do |user_id|
        collaborators << {
            wiki_id: wiki.id,
            user_id: user_id}
    end

    Collaborator.create(collaborators)
    redirect_to wiki_collaborators_path(wiki)
  end
end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController
  def new
  end

  def update
    current_user.update_attribute(standard: true, premium: false)

    flash[:notice] = "Your account has been downgraded. You may come back anytime and upgrade."

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def show
      @user = User.find(params[:id])
  end

  def update
      user = User.find(params[:id])
      user.assign_attributes(user_params)

      if user.save
          render json: user
      else
          render json: {}, status: :unprocessable_entity
      end
  end

  private

  def user_params
      params.require(:user).permit(:email)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_filter :authenticate_user!, only: [:index, :about]

    def index
    end

    def about
    end
 end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_filter :authenticate_user!, except: [:index, :show]
  after_action :verify_policy_scoped, only: :index

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.create(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error creating your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
        flash[:notice] = "Wiki was updated"
        redirect_to @wiki
    else
        flash.now[:alert] = "Error saving wiki. Please try again."
        render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
        flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
        redirect_to wikis_path
    else
        flash.now[:alert] = "There was an error deleting the wiki"
        render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      prettify: true,
      hard_wrap: true,
      safe_links_only: true,
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      superscript: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    @markdown ||= Redcarpet::Markdown.new(renderer, extensions)

    @markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrades_helper.rb
module DowngradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_can_upgrade?(user)
        current_user == user && current_user.role == 'standard'
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
 <h4>Click here to upgrade your Blocipedia Account to Premium</h4>
 <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
 data-key="<%= @stripe_btn_data[:key] %>"
 data-amount=<%= @stripe_btn_data[:amount] %>
 data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/collaborators/index.html.erb
<h1>All Collaborators for <%= @wiki.title %> Wiki </h1>

<ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborate_users %></ul>

<p><%= link_to "Return to Wiki", wiki_path(@wiki), class: 'btn btn-success' %></p>

app/views/collaborators/new.html.erb
<h2>Add collaborators to <%= @wiki.title %>:</h2>

<%= form_tag(wiki_collaborators_path(wiki_id: @wiki), method: :post) do %>
  <table class="users_table">
    <tr>
      <th>User</th>
      <th>Give Access?</th>
    </tr>
    <% User.all.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= check_box_tag('collaborators[]', user.id, @wiki.collaborate_users.include?(user), {multiple: true}) %></td>
      </tr>
    <% end %>
  </table>
  <p><%= submit_tag("Save", class: 'btn btn-success', data: {confirm: "Are you sure you want to add/remove these collaborators?"}) %></p>
<% end %>

app/views/downgrades/new.html.erb
<h4>Would you like to downgrade your account back to standard?</h4>
<p>Don't forget, you will have to pay another $15 to get Premium features back on your account. Choose wisely.</p>
<%= link_to "Downgrade Your Account", downgrade_create_path, method: :create, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
       <ul class="nav nav-tabs">
          <li><%= link_to "Blocipedia", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Wikis", wikis_path %></li>
       <div class="pull-right">
          <% if user_signed_in? %>
            <div class="pull-right">
              <ul class="nav nav-tabs">
                <li class="username">Signed in as: <strong><%= current_user.email %></strong></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <% if current_user.standard? %>
                  <li><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %></li>
                <% elsif current_user.premium? %>
                  <li><%= link_to 'Downgrade Your Account', new_downgrade_path, :class => 'navbar-link' %></li>
                <% end %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </div>
          <% else %>
            <div class="pull-right">
              <ul class="nav nav-tabs", style="border-bottom:0px;">
                <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
              </ul>
            </div>
          <% end %>
         </div>
       </ul>

       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
  <h1>Blocipedia: Social, Markdown Wikis</h1>
  <h3>Create and share Markdown Wikis</h3>
    <p>
     <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-success' %> <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-default' %>
     <% else %>
      <%= link_to "New Wiki", new_wiki_path, :class => 'btn btn-success' %>
     <% end %>
    </p>
 </div>

 <div class="row icons">
   <div class="col-md-6">
     <p>Create as many public wikis as you want!</p>
     <a href="/users/sign_up"<span class="glyphicon glyphicon-eye-open"></span></a><br>
     Free Plan
   </div>
   <div class="col-md-6">
     <p>Create private wikis!</p>
     <a href="charges/new"<span class="glyphicon glyphicon-eye-close"></span></a><br>
     Premium Plan
   </div>
 </div>

app/views/wikis/_collaborator.html.erb
<li><%= collaborator.email %></li>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter wiki body" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
       <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
                <%= f.check_box :private %> Private wiki
            <% end %>
        </div>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/wikis/create.html.erb
<h1>Create New Wiki</h1>
<h1>New Wiki</h1>

<div class="col-md-6">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="col-md-6">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% if @wikis.any? %>
      <% @wikis.each do |wiki| %>
        <div>
          <% if !wiki.private? || (wiki.private? && current_user.present?) %>
            <h4><%= link_to wiki.title, wiki %></h4>
            <small>submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.email %></small>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <h4>Help us create some Wikis!</h4>
      <br>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= button_to "Create Wiki", new_wiki_path, class:"btn btn-success", method: :get %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Create New Wiki</h1>
<h1>New Wiki</h1>

<div class="col-md-6">
    <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/show.html.erb
<h1>
    <%= @wiki.title %> <br>
    <small>
        submitted <%= time_ago_in_words(@wiki.created_at) %> ago
    </small>
    <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-primary' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
</h1>
<p><%= markdown(@wiki.body) %> </p>
<p>Created by: <%= @wiki.user.email %></p>
<div>
  <% if @wiki.private %>
    <h4>Collaborators:</h4>
    <p><%= link_to "Add/Remove collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-default' %></p>
    <ul><%= render partial: 'wikis/collaborator', collection: @wiki.collaborate_users %></ul>
  <% end %>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>